repository:
  git: git@github.com:pismo/api-gateway-e2e-test
  branch: canary-api


components:
- name: auth-api
  workdir: src/auth-api
  git: git@github.com:pismo/auth-api
  componentdir: auth-api
- name: certificates-api
  workdir: src/certificates-api
  commponentdir: certificates-api
  git: git@github.com:pismo/certificates-api
- name: echo-server
  workdir: src/echo-server
- name: jwt-builder
  workdir: src/jwt-builder
- name: mysql
  workdir: src/mysql
- name: recaptcha-client
  workdir: src/setup
- name: token-helper
  workdir: src/token-helper
- name: zuul
  workdir: src/zuul
  componentdir: pismo-zuul-gateway
  git: git@github.com:pismo/pismo-zuul-gateway
- name: aws-cli
  workdir: src/aws-cli
- name: dynamodb
  workdir: src/dynamodb
- name: kong
  workdir: src/kong
  componentdir: api-gateway
  git: git@github.com:pismo/api-gateway
- name: mockserver
  workdir: src/mockserver
- name: passport-api
  workdir: src/passport-api
  git: git@github.com:pismo/passport-api
- name: redis
  workdir: src/redis
- name: token-generator-service
  workdir: src/token-generator-service
- name: tools
  workdir: src/tools